rm CeasarCipher.class
rm CeasarCipher.java
rm README.md
rm installer.sh
rm uninstaller.sh
cd ..
rmdir Ceaser_Cipher_encrypt-decrypt/Waterwolf9910-ScienceFair2019
cd ..
rmdir Ceaser_Cipher_encrypt-decrypt
exit 0
