rm CaesarCipher.class
rm CaesarCipher.java
rm README.md
rm installer.sh
rm uninstaller.sh
cd ..
rmdir Caeser_Cipher_encrypt-decrypt/Waterwolf9910-ScienceFair2019
cd ..
rmdir Caeser_Cipher_encrypt-decrypt
exit 0
